services:
  app-service:
    extends:
      file: ./app-service/compose.dev.yml
      service: app-service

  auth-service:
    extends:
      file: ./auth-service/compose.dev.yml
      service: auth-service

  db:
    extends:
      file: ./auth-service/compose.dev.yml
      service: db

  redis:
    extends:
      file: ./auth-service/compose.dev.yml
      service: redis

  reverse-proxy:
    extends:
      file: ./reverse-proxy/compose.dev.yml
      service: reverse-proxy

volumes:
  auth-config:
    name: project_auth_config
  db:
    name: project_db
    driver: local
  caddy_data:
    name: project_caddy_data
  caddy_config:
    name: project_caddy_config

networks:
  internal:
    name: project_internal
  backend:
    name: project_backend
