services:
  app-service:
    build:
      context: ./app-service/
      dockerfile: ./Dockerfile

  auth-service:
    build:
      context: ./auth-service/
      dockerfile: ./Dockerfile
    volumes: !override
      - ./auth-service/config:/app/config

  reverse-proxy:
    volumes: !override
      - ./reverse-proxy/.config/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports: !override
      - "8080:8080"
