services:
  app-service:
    build:
      context: . # specify directory where local Dockerfile is located
      dockerfile: ./app-service/Dockerfile

  auth-service:
    build:
      context: . # specify directory where local Dockerfile is located
      dockerfile: ./auth-service/Dockerfile
