services:
  auth-service:
    image: aleanton/auth-service
    restart: "always"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_ELEVATED_SECRET: ${JWT_ELEVATED_SECRET}
      AUTH_SERVICE_ALLOWED_ORIGINS: ${AUTH_SERVICE_ALLOWED_ORIGINS}
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
      REDIS_HOST_NAME: ${REDIS_HOST_NAME}
    expose:
      - "3000"
    networks:
      - internal
      - backend
    volumes:
      - "auth-config:/config"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started

  db:
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    networks:
      - internal
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    restart: always
    expose:
      - "6379"
    networks:
      - internal

volumes:
  auth-config:
  db:
    driver: local

networks:
  internal:
    driver: bridge
  backend:
    external: true
    name: project_backend
