services:
  reverse-proxy:
    image: caddy:2
    volumes:
      - ./.config/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

volumes:
  caddy_data:
  caddy_config:

networks:
  backend:
    external: true
    name: project_backend
